title: Dedunu Dhananjaya 
author:
  name: Dedunu Dhananjaya
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  Powered by Github

show_excerpts: false 

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: dedunumax
    linkedin: dedunu 

header_pages:
 - info.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
