title: Dedunu Dhananjaya 
author:
  name: Dedunu Dhananjaya
  email: 
description: > 
  Powered by Github

show_excerpts: false 

paginate: 5
paginate_path: "/blog/page:num/"

minima:
  date_format: "%-d %B %Y"
  
  social_links:
    github: dedunumax
    linkedin: dedunu 

header_pages:
 - info.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
