# Site settings
title: Dedunu Dhananjaya
name: Dedunu Dhananjaya
author: Dedunu Dhananjaya
email: admin@dedunu.info
description: > # this means to ignore newlines until "baseurl:"
  &lt;code&gt; learn &lt;/share&gt;
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dedunumax.info" # the base hostname & protocol for your site
twitter_username: dedunumax
github_username:  dedunumax

# Build settings
markdown: kramdown
